from django.conf import settings


SUBSCRIPTION_GRACE_PERIOD= getattr(settings, 'SUBSCRIPTION_GRACE_PERIOD', 2)

SUBSCRIPTION_GROUP_BASED_PERMISSIONS= getattr(settings, 'SUBSCRIPTION_GROUP_BASED_PERMISSIONS', True)
SUBSCRIPTION_GENERIC_MODEL_BASED_PERMISSIONS= getattr(settings, 'SUBSCRIPTION_GENERIC_MODEL_BASED_PERMISSIONS', False)
SUBSCRIPTION_GENERIC_MODEL_PERMISSIONS= getattr(settings, 'SUBSCRIPTION_GENERIC_MODEL_PERMISSIONS', None)